# Generated by Django 6.0.1 on 2026-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Cash on Delivery", max_length=20),
            preserve_default=False,
        ),
    ]
