# Generated by Django 6.0.1 on 2026-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
