# Generated by Django 6.0.1 on 2026-01-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_order_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_method",
            new_name="payment",
        ),
    ]
