# Generated by Django 4.2 on 2026-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=200)),
            ],
        ),
    ]
