# Generated by Django 4.2 on 2026-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
